import math

#Particles
NBR_TRIANGLE_IN_CIRCLE = 5
CIRCLE_RADIUS = 3
SUN_PARTICLE_RADIUS = 5
PARTICLE_COLOR = (173, 216, 230)
SUN_PARTICLE_COLOR = (255, 255, 0)
SUN_PARTICLE_COLOR_DELTA = 150
MIN_PARTICLES = 100
MAX_PARTICLES = 100
MIN_SUN_PARTICLES = 300
MAX_SUN_PARTICLES = 300
GRAVITY_MAGNITUDE = 9.81
GRAVITY_DIRECTION = math.pi / 2
SUN_GRAVITY_MAGNITUDE = 1
MARGIN_SUN_PARTICLES = 100

#Music process
midi_file = "Ecossaise_Beethoven.midi"
mp3_file = "Ecossaise_Both.mp3"